CREATE OR REPLACE VIEW vami_SELLIN AS

SELECT DFM.SEQFORNECEDOR CODFORNEC, DFM.FORNECEDOR, NF.SEQPRODUTO, QP.PRODUTO DESCRICAO,
       NF.NUMERONF, NF.DTAEMISSAO, NF.QUANTIDADE QTDITEM, NF.VLRITEM, NULL VLRLIQ, NF.VLRICMSST, FC.VLRIPI,
       DV.QUANTIDADE QTDEDEV, DV.VLRDEVOLUCAO VLRDEV, NF.DTAENTRADA, NULL NROPED
       
FROM DWNAGT_NFLOJAMATRIZ NF
         LEFT JOIN QLV_PRODUTO QP ON NF.SEQPRODUTO = QP.SEQPRODUTO
         LEFT JOIN DIM_FORNECEDOR DFM ON NF.SEQPESSOA = DFM.SEQFORNECEDOR
         LEFT JOIN DWNAGT_NFDEVOLUCOES DV ON NF.NUMERONF = DV.NOTA AND DV.SEQPRODUTO = NF.SEQPRODUTO
         LEFT JOIN FATO_COMPRA FC ON NF.NROEMPRESA = FC.NROEMPRESA AND FC.SEQPRODUTO = NF.SEQPRODUTO AND FC.DTAENTRADA = NF.DTAENTRADA
                   AND FC.QTDITEM = NF.QUANTIDADE AND FC.VLRITEM = NF.VLRITEM
         
        /* WHERE NF.DTAENTRADA BETWEEN DATE '2022-05-01' AND DATE '2022-05-20'*/
           WHERE NF.STATUSNF != 'C'
ORDER BY NF.DTAENTRADA, NF.NUMERONF DESC

);
