CREATE OR REPLACE VIEW vami_EMPRESA AS (

SELECT  DE.NROEMPRESA NROEMP, DE.FANTASIA EMPRESA, DE.UF, DE.CEP, DE.CIDADE, 
        CASE WHEN NROEMPRESA IN (500,501,502,504,505,506) THEN 'CD'
             WHEN NROEMPRESA IN (600,601,602,603) THEN 'ADM'
             WHEN EMPRESA LIKE ('%INATIVO%') OR EMPRESA LIKE ('%MAKTUB%') THEN 'INATIVO'
             ELSE 'LOJA' 
        END FORMATO, NULL DTA_ABERTURA, NULL DTA_FECHAMENTO, DE.REGIAO,
        CASE WHEN DE.NROEMPRESA IN (500,501,502,504,505,506) THEN 'CD' 
             WHEN DE.NROEMPRESA IN (600,601,602,603) THEN 'ADM'
             WHEN EMPRESA LIKE '%MERC%' THEN 'ATACAREJO'
             WHEN EMPRESA LIKE ('%INATIVO%') OR EMPRESA LIKE ('%MAKTUB%') THEN 'INATIVO'
             ELSE 'SUPERMERCADO' END TIPO
        
FROM DIM_EMPRESA DE

ORDER BY 1 ASC

);
