
SELECT QP.SEQPRODUTO PLU, QP.PRODUTO DESCRICAO, DPC.CODACESSO EAN, 
       QC.CATEGORIA_NIVEL_1 N1, QC.CATEGORIA_NIVEL_2 N2, QC.CATEGORIA_NIVEL_3 N3, QC.CATEGORIA_NIVEL_4 N4, QC.CATEGORIA_NIVEL_5 N5,
       CASE WHEN UPPER(QP.MARCA) LIKE '%NAGUMO%' THEN 'S' ELSE 'N' END MARCA_PROPRIA,
       QP.FORNECEDOR_PRINCIPAL FORNECEDOR, QP.SEQFORNECEDOR_PRINCIPAL,
       LPAD(DFR.NROCGCCPF,12,0)||LPAD(DFR.DIGCGCCPF,2,0) CNPJ_FORNEC, QP.MARCA, 
       DECODE(QE.STATUS_VENDA, 'A','Ativo','I','Inativo','S','Suspenso') STATUS_VDA
       
FROM QLV_PRODUTO QP LEFT JOIN DIM_PRODUTOCODIGO DPC ON QP.SEQPRODUTO = DPC.SEQPRODUTO AND DPC.QTDEMBALAGEM = 1 AND DPC.TIPCODIGO = 'E'
                    LEFT JOIN QLV_CATEGORIA     QC  ON QP.SEQFAMILIA = QC.SEQFAMILIA
                    LEFT JOIN DIM_FORNECEDOR    DFR ON QP.SEQFORNECEDOR_PRINCIPAL = DFR.SEQFORNECEDOR
                    LEFT JOIN QLV_PRODUTOEMPRESA QE ON QP.SEQPRODUTO = QE.SEQPRODUTO  AND QE.NRO_EMPRESA = 8

-- WHERE QP.SEQPRODUTO IN (5500, 212257, 19439, 245402)
